* configure.in: Make --disable-jemacs the default. 	(--enable-brl): New non-default flag. 	* build.xml (brl-classes): Split new target off from xml-classes. 	(enable-brl): New property. 	(enable-jemacs): Make default false. 	* build.properties (enable-jemacs, enable-brl): Update to match. 	* Makefile.am: Conditionalize on ENABLE_JEMACS and ENABLE_BRL. 	* gnu/jemacs/*/Makefile.am: Remove condionalization on 	ENABLE_JEMACS, since handled in top-level Makefile.
git-svn-id: svn://sourceware.org/svn/kawa/trunk@5817 5e0a886f-7f45-49c5-bc19-40643649e37f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -689,7 +689,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar JAVA_SOURCE LN_S CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LIBTOOL SED GREP EGREP FGREP LD NM AR ac_ct_AR RANLIB ac_ct_RANLIB lt_ECHO CPP CXXCPP GCJ ac_ct_GCJ GCJFLAGS GCJDEPMODE am__fastdepGCJ_TRUE am__fastdepGCJ_FALSE LIBTOOL_DEPS WITH_GCJ_TRUE WITH_GCJ_FALSE WITH_GCJ_DBTOOL_TRUE WITH_GCJ_DBTOOL_FALSE ENABLE_ECHO2_TRUE ENABLE_ECHO2_FALSE ENABLE_JEMACS_TRUE ENABLE_JEMACS_FALSE ENABLE_XML_TRUE ENABLE_XML_FALSE ENABLE_SERVLET_TRUE ENABLE_SERVLET_FALSE WITH_SWING_TRUE WITH_SWING_FALSE WITH_SWT_TRUE WITH_SWT_FALSE WITH_AWT_TRUE WITH_AWT_FALSE WITH_SAX2_TRUE WITH_SAX2_FALSE WITH_XQTS_TRUE WITH_XQTS_FALSE ENABLE_KAWA_FRONTEND_TRUE ENABLE_KAWA_FRONTEND_FALSE XQTS_PATH SAX2_PREPROCESS conf_classpath pathsep filesep JAVA JAVAC JAVACFLAGS GCJ_COMPILED_SELECTED GCJ_SELECTED TOP_BUILDDIR JEMACS_VERSION BYTECODE_VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar JAVA_SOURCE LN_S CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LIBTOOL SED GREP EGREP FGREP LD NM AR ac_ct_AR RANLIB ac_ct_RANLIB lt_ECHO CPP CXXCPP GCJ ac_ct_GCJ GCJFLAGS GCJDEPMODE am__fastdepGCJ_TRUE am__fastdepGCJ_FALSE LIBTOOL_DEPS WITH_GCJ_TRUE WITH_GCJ_FALSE WITH_GCJ_DBTOOL_TRUE WITH_GCJ_DBTOOL_FALSE ENABLE_ECHO2_TRUE ENABLE_ECHO2_FALSE ENABLE_BRL_TRUE ENABLE_BRL_FALSE ENABLE_JEMACS_TRUE ENABLE_JEMACS_FALSE ENABLE_XML_TRUE ENABLE_XML_FALSE ENABLE_SERVLET_TRUE ENABLE_SERVLET_FALSE WITH_SWING_TRUE WITH_SWING_FALSE WITH_SWT_TRUE WITH_SWT_FALSE WITH_AWT_TRUE WITH_AWT_FALSE WITH_SAX2_TRUE WITH_SAX2_FALSE WITH_XQTS_TRUE WITH_XQTS_FALSE ENABLE_KAWA_FRONTEND_TRUE ENABLE_KAWA_FRONTEND_FALSE XQTS_PATH SAX2_PREPROCESS conf_classpath pathsep filesep JAVA JAVAC JAVACFLAGS GCJ_COMPILED_SELECTED GCJ_SELECTED TOP_BUILDDIR JEMACS_VERSION BYTECODE_VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files='Make_rules'
 
 # Initialize some variables set by options.
@@ -1253,6 +1253,7 @@ Optional Features:
   --disable-xml           Don't build support for XML processing
   --enable-echo2          Enable support for the Echo2 web toolkit
   --enable-jemacs         Build JEmacs
+  --enable-brl            Build BRL emulation and KRL
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-shared[=PKGS]
@@ -2358,9 +2359,13 @@ fi;
 # Check whether --enable-jemacs or --disable-jemacs was given.
 if test "${enable_jemacs+set}" = set; then
   enableval="$enable_jemacs"
-  enable_jemacs=$enableval
-else
-  enable_jemacs=yes
+
+fi;
+
+# Check whether --enable-brl or --disable-brl was given.
+if test "${enable_brl+set}" = set; then
+  enableval="$enable_brl"
+
 fi;
 
 
@@ -7022,7 +7027,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 7025 "configure"
+#line 7030 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7120,7 +7125,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 7123 "configure"
+#line 7128 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7269,7 +7274,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  $ECHO '#line 7272 "configure"' > conftest.$ac_ext
+  $ECHO '#line 7277 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8707,11 +8712,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8710: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8715: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8714: \$? = $ac_status" >&5
+   echo "$as_me:8719: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8994,11 +8999,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8997: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9002: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9001: \$? = $ac_status" >&5
+   echo "$as_me:9006: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -9091,11 +9096,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9094: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9099: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9098: \$? = $ac_status" >&5
+   echo "$as_me:9103: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9145,11 +9150,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9148: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9153: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9152: \$? = $ac_status" >&5
+   echo "$as_me:9157: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12748,11 +12753,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12751: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12756: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12755: \$? = $ac_status" >&5
+   echo "$as_me:12760: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12839,11 +12844,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12842: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12847: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12846: \$? = $ac_status" >&5
+   echo "$as_me:12851: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12890,11 +12895,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12893: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12898: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12897: \$? = $ac_status" >&5
+   echo "$as_me:12902: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13995,11 +14000,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13998: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14003: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14002: \$? = $ac_status" >&5
+   echo "$as_me:14007: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14276,11 +14281,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14279: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14284: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14283: \$? = $ac_status" >&5
+   echo "$as_me:14288: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14367,11 +14372,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14370: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14375: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14374: \$? = $ac_status" >&5
+   echo "$as_me:14379: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14418,11 +14423,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14421: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14426: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14425: \$? = $ac_status" >&5
+   echo "$as_me:14430: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16391,6 +16396,16 @@ fi
 
 
 
+if test "$enable_brl" = "yes"; then
+  ENABLE_BRL_TRUE=
+  ENABLE_BRL_FALSE='#'
+else
+  ENABLE_BRL_TRUE='#'
+  ENABLE_BRL_FALSE=
+fi
+
+
+
 if test "$enable_jemacs" = "yes"; then
   ENABLE_JEMACS_TRUE=
   ENABLE_JEMACS_FALSE='#'
@@ -16712,6 +16727,13 @@ if test -z "${ENABLE_ECHO2_TRUE}" && test -z "${ENABLE_ECHO2_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_ECHO2\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_ECHO2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_BRL_TRUE}" && test -z "${ENABLE_BRL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_BRL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_BRL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17684,6 +17706,8 @@ s,@WITH_GCJ_DBTOOL_TRUE@,$WITH_GCJ_DBTOOL_TRUE,;t t
 s,@WITH_GCJ_DBTOOL_FALSE@,$WITH_GCJ_DBTOOL_FALSE,;t t
 s,@ENABLE_ECHO2_TRUE@,$ENABLE_ECHO2_TRUE,;t t
 s,@ENABLE_ECHO2_FALSE@,$ENABLE_ECHO2_FALSE,;t t
+s,@ENABLE_BRL_TRUE@,$ENABLE_BRL_TRUE,;t t
+s,@ENABLE_BRL_FALSE@,$ENABLE_BRL_FALSE,;t t
 s,@ENABLE_JEMACS_TRUE@,$ENABLE_JEMACS_TRUE,;t t
 s,@ENABLE_JEMACS_FALSE@,$ENABLE_JEMACS_FALSE,;t t
 s,@ENABLE_XML_TRUE@,$ENABLE_XML_TRUE,;t t
