* configure.in (WITH_GCJ_NO_DBTOOL): New conditional. In bin: 	* Makefile.am: A number of changes to avoid using libtool - except 	when WITH_LIBTOOL is selected.  Various 'install' fixes. 	(LIBADD_BRL): Don't add brl.o files unless we --enable-brl. 	(kawa.sh): Fix WITH_GCJ_NO_DBTOOL case. 	(WITH_GCJ_LIBS, WITHOUT_GCJ_LIBS): Remove unused macros. Various: 	* Makefile.am (KAWA): Use bin's kawa.sh directly. 	(various *.class): We need to set CLASSPATH explicitly now.
git-svn-id: svn://sourceware.org/svn/kawa/trunk@5882 5e0a886f-7f45-49c5-bc19-40643649e37f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -504,7 +504,7 @@ PACKAGE_STRING='kawa 1.9.1'
 PACKAGE_BUGREPORT=''
 
 ac_unique_file="doc/kawa.texi"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar JAVA_SOURCE LN_S CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE GCJ ac_ct_GCJ GCJFLAGS GCJDEPMODE am__fastdepGCJ_TRUE am__fastdepGCJ_FALSE WITH_GCJ_TRUE WITH_GCJ_FALSE WITH_GCJ_DBTOOL_TRUE WITH_GCJ_DBTOOL_FALSE ENABLE_ECHO2_TRUE ENABLE_ECHO2_FALSE ENABLE_BRL_TRUE ENABLE_BRL_FALSE ENABLE_JEMACS_TRUE ENABLE_JEMACS_FALSE ENABLE_XML_TRUE ENABLE_XML_FALSE ENABLE_SERVLET_TRUE ENABLE_SERVLET_FALSE WITH_SWING_TRUE WITH_SWING_FALSE WITH_SWT_TRUE WITH_SWT_FALSE WITH_AWT_TRUE WITH_AWT_FALSE WITH_SAX2_TRUE WITH_SAX2_FALSE WITH_XQTS_TRUE WITH_XQTS_FALSE ENABLE_KAWA_FRONTEND_TRUE ENABLE_KAWA_FRONTEND_FALSE WITH_LIBTOOL_TRUE WITH_LIBTOOL_FALSE XQTS_PATH SAX2_PREPROCESS conf_classpath pathsep filesep JAVA JAVAC JAVACFLAGS GCJ_COMPILED_SELECTED GCJ_SELECTED TOP_BUILDDIR JEMACS_VERSION BYTECODE_VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar JAVA_SOURCE LN_S CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE GCJ ac_ct_GCJ GCJFLAGS GCJDEPMODE am__fastdepGCJ_TRUE am__fastdepGCJ_FALSE WITH_GCJ_TRUE WITH_GCJ_FALSE WITH_GCJ_DBTOOL_TRUE WITH_GCJ_DBTOOL_FALSE WITH_GCJ_NO_DBTOOL_TRUE WITH_GCJ_NO_DBTOOL_FALSE ENABLE_ECHO2_TRUE ENABLE_ECHO2_FALSE ENABLE_BRL_TRUE ENABLE_BRL_FALSE ENABLE_JEMACS_TRUE ENABLE_JEMACS_FALSE ENABLE_XML_TRUE ENABLE_XML_FALSE ENABLE_SERVLET_TRUE ENABLE_SERVLET_FALSE WITH_SWING_TRUE WITH_SWING_FALSE WITH_SWT_TRUE WITH_SWT_FALSE WITH_AWT_TRUE WITH_AWT_FALSE WITH_SAX2_TRUE WITH_SAX2_FALSE WITH_XQTS_TRUE WITH_XQTS_FALSE ENABLE_KAWA_FRONTEND_TRUE ENABLE_KAWA_FRONTEND_FALSE WITH_LIBTOOL_TRUE WITH_LIBTOOL_FALSE XQTS_PATH SAX2_PREPROCESS conf_classpath pathsep filesep JAVA JAVAC JAVACFLAGS GCJ_COMPILED_SELECTED GCJ_SELECTED TOP_BUILDDIR JEMACS_VERSION BYTECODE_VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files='Make_rules'
 
 # Initialize some variables set by options.
@@ -4410,6 +4410,16 @@ fi
 
 
 
+if test "$with_gcj" = "yes" -a "$with_gcj_dbtool" != "yes"; then
+  WITH_GCJ_NO_DBTOOL_TRUE=
+  WITH_GCJ_NO_DBTOOL_FALSE='#'
+else
+  WITH_GCJ_NO_DBTOOL_TRUE='#'
+  WITH_GCJ_NO_DBTOOL_FALSE=
+fi
+
+
+
 if test "$enable_echo2" = "yes"; then
   ENABLE_ECHO2_TRUE=
   ENABLE_ECHO2_FALSE='#'
@@ -4747,6 +4757,13 @@ if test -z "${WITH_GCJ_DBTOOL_TRUE}" && test -z "${WITH_GCJ_DBTOOL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"WITH_GCJ_DBTOOL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WITH_GCJ_DBTOOL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_GCJ_NO_DBTOOL_TRUE}" && test -z "${WITH_GCJ_NO_DBTOOL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_GCJ_NO_DBTOOL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_GCJ_NO_DBTOOL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5478,6 +5495,8 @@ s,@WITH_GCJ_TRUE@,$WITH_GCJ_TRUE,;t t
 s,@WITH_GCJ_FALSE@,$WITH_GCJ_FALSE,;t t
 s,@WITH_GCJ_DBTOOL_TRUE@,$WITH_GCJ_DBTOOL_TRUE,;t t
 s,@WITH_GCJ_DBTOOL_FALSE@,$WITH_GCJ_DBTOOL_FALSE,;t t
+s,@WITH_GCJ_NO_DBTOOL_TRUE@,$WITH_GCJ_NO_DBTOOL_TRUE,;t t
+s,@WITH_GCJ_NO_DBTOOL_FALSE@,$WITH_GCJ_NO_DBTOOL_FALSE,;t t
 s,@ENABLE_ECHO2_TRUE@,$ENABLE_ECHO2_TRUE,;t t
 s,@ENABLE_ECHO2_FALSE@,$ENABLE_ECHO2_FALSE,;t t
 s,@ENABLE_BRL_TRUE@,$ENABLE_BRL_TRUE,;t t
