* Make-rules: New automake doesn't seem to set DIST_SOURCES from 	SOURCES, so undefine SOURCES and define DISTFILES explicitly.
	* configure.in: New --with-java-source flag, sets @JAVA_SOURCE@.
	* Makefile.am (java1-java2-files): Rename to patch-source-list and
	generailize to also look for JAVA5 and JAXP conditionals.
	(selected-java-source, select-java5, dist-hook): New rules.

	* Makefile.am (makekawa.bar): Remove bit-rotted rule.


git-svn-id: svn://sourceware.org/svn/kawa/trunk@4094 5e0a886f-7f45-49c5-bc19-40643649e37f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar LN_S CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE GCJ ac_ct_GCJ GCJFLAGS EGREP ECHO RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL GCJDEPMODE am__fastdepGCJ_TRUE am__fastdepGCJ_FALSE LIBTOOL_DEPS WITH_GCJ_TRUE WITH_GCJ_FALSE ENABLE_XML_TRUE ENABLE_XML_FALSE ENABLE_SERVLET_TRUE ENABLE_SERVLET_FALSE WITH_SWING_TRUE WITH_SWING_FALSE WITH_SWT_TRUE WITH_SWT_FALSE WITH_AWT_TRUE WITH_AWT_FALSE WITH_SAX2_TRUE WITH_SAX2_FALSE ENABLE_KAWA_FRONTEND_TRUE ENABLE_KAWA_FRONTEND_FALSE conf_classpath pathsep filesep JAVA JAVAC XML_SELECTED AWT_SELECTED SWING_SELECTED GCJ_COMPILED_SELECTED GCJ_SELECTED extra_java TOP_BUILDDIR JEMACS_VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar JAVA_SOURCE LN_S CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE GCJ ac_ct_GCJ GCJFLAGS EGREP ECHO RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL GCJDEPMODE am__fastdepGCJ_TRUE am__fastdepGCJ_FALSE LIBTOOL_DEPS WITH_GCJ_TRUE WITH_GCJ_FALSE ENABLE_XML_TRUE ENABLE_XML_FALSE ENABLE_SERVLET_TRUE ENABLE_SERVLET_FALSE WITH_SWING_TRUE WITH_SWING_FALSE WITH_SWT_TRUE WITH_SWT_FALSE WITH_AWT_TRUE WITH_AWT_FALSE WITH_SAX2_TRUE WITH_SAX2_FALSE ENABLE_KAWA_FRONTEND_TRUE ENABLE_KAWA_FRONTEND_FALSE conf_classpath pathsep filesep JAVA JAVAC XML_SELECTED AWT_SELECTED SWING_SELECTED GCJ_COMPILED_SELECTED GCJ_SELECTED extra_java TOP_BUILDDIR JEMACS_VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files='Make_rules'
 
 # Initialize some variables set by options.
@@ -1050,6 +1050,7 @@ Optional Packages:
   --with-swt              Assume SWT is available
   --with-awt              Assume AWT is available (default on)
   --with-sax2             Assume SAX2 is available
+  --with-java-source=NUM  Assume functionality of given Java/JDK version
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -2053,6 +2054,90 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 
 
 
+# Check whether --enable-kawa-frontend or --disable-kawa-frontend was given.
+if test "${enable_kawa_frontend+set}" = set; then
+  enableval="$enable_kawa_frontend"
+  enable_kawa_frontend=$enableval
+else
+  enable_kawa_frontend=no
+fi;
+
+
+# Check whether --with-gcj or --without-gcj was given.
+if test "${with_gcj+set}" = set; then
+  withval="$with_gcj"
+
+fi;
+
+# Check whether --enable-xml or --disable-xml was given.
+if test "${enable_xml+set}" = set; then
+  enableval="$enable_xml"
+  enable_xml=$enableval
+else
+  enable_xml=yes
+fi;
+
+
+# Check whether --with-servlet or --without-servlet was given.
+if test "${with_servlet+set}" = set; then
+  withval="$with_servlet"
+  with_servlet=$withval
+else
+  with_servlet=no
+fi;
+
+
+# Check whether --with-swing or --without-swing was given.
+if test "${with_swing+set}" = set; then
+  withval="$with_swing"
+
+fi;
+
+
+# Check whether --with-swt or --without-swt was given.
+if test "${with_swt+set}" = set; then
+  withval="$with_swt"
+
+fi;
+
+
+# Check whether --with-awt or --without-awt was given.
+if test "${with_awt+set}" = set; then
+  withval="$with_awt"
+
+fi;
+
+
+# Check whether --with-sax2 or --without-sax2 was given.
+if test "${with_sax2+set}" = set; then
+  withval="$with_sax2"
+
+fi;
+
+
+# Check whether --with-java-source or --without-java-source was given.
+if test "${with_java_source+set}" = set; then
+  withval="$with_java_source"
+
+fi;
+
+case "/${with_java_source}/" in
+  /1/) JAVA_SOURCE=1 ;;
+  /2/) JAVA_SOURCE=2 ;;
+  /5/) JAVA_SOURCE=5 ;;
+  /1.1*/) JAVA_SOURCE=1 ;;
+  /1.2*/) JAVA_SOURCE=2 ;;
+  /1.3*/) JAVA_SOURCE=2 ;;
+  /1.4*/) JAVA_SOURCE=2 ;;
+  //) JAVA_SOURCE=2 ;;
+  /*/) { { echo "$as_me:$LINENO: error: Invalid version for --with-java-version.
+  (Must be 1, 2, 5, or a JDK version such as 1.4.)" >&5
+echo "$as_me: error: Invalid version for --with-java-version.
+  (Must be 1, 2, 5, or a JDK version such as 1.4.)" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+
+
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
 # incompatible versions:
@@ -2146,66 +2231,6 @@ fi
 
 
 
-
-# Check whether --enable-kawa-frontend or --disable-kawa-frontend was given.
-if test "${enable_kawa_frontend+set}" = set; then
-  enableval="$enable_kawa_frontend"
-  enable_kawa_frontend=$enableval
-else
-  enable_kawa_frontend=no
-fi;
-
-
-# Check whether --with-gcj or --without-gcj was given.
-if test "${with_gcj+set}" = set; then
-  withval="$with_gcj"
-
-fi;
-
-# Check whether --enable-xml or --disable-xml was given.
-if test "${enable_xml+set}" = set; then
-  enableval="$enable_xml"
-  enable_xml=$enableval
-else
-  enable_xml=yes
-fi;
-
-
-# Check whether --with-servlet or --without-servlet was given.
-if test "${with_servlet+set}" = set; then
-  withval="$with_servlet"
-  with_servlet=$withval
-else
-  with_servlet=no
-fi;
-
-
-# Check whether --with-swing or --without-swing was given.
-if test "${with_swing+set}" = set; then
-  withval="$with_swing"
-
-fi;
-
-
-# Check whether --with-swt or --without-swt was given.
-if test "${with_swt+set}" = set; then
-  withval="$with_swt"
-
-fi;
-
-
-# Check whether --with-awt or --without-awt was given.
-if test "${with_awt+set}" = set; then
-  withval="$with_awt"
-
-fi;
-
-
-# Check whether --with-sax2 or --without-sax2 was given.
-if test "${with_sax2+set}" = set; then
-  withval="$with_sax2"
-
-fi;
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4424,7 +4449,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4427 "configure"' > conftest.$ac_ext
+  echo '#line 4452 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5518,7 +5543,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5521:" \
+echo "$as_me:5546:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6470,11 +6495,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6473: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6498: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6477: \$? = $ac_status" >&5
+   echo "$as_me:6502: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6682,11 +6707,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6685: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6710: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6689: \$? = $ac_status" >&5
+   echo "$as_me:6714: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6749,11 +6774,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6752: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6777: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6756: \$? = $ac_status" >&5
+   echo "$as_me:6781: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8691,7 +8716,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8694 "configure"
+#line 8719 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8789,7 +8814,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8792 "configure"
+#line 8817 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10720,11 +10745,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10723: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10748: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10727: \$? = $ac_status" >&5
+   echo "$as_me:10752: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10787,11 +10812,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10790: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10794: \$? = $ac_status" >&5
+   echo "$as_me:10819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11988,7 +12013,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11991 "configure"
+#line 12016 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12086,7 +12111,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12089 "configure"
+#line 12114 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12849,11 +12874,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12852: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12877: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12856: \$? = $ac_status" >&5
+   echo "$as_me:12881: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12916,11 +12941,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12919: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12944: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12923: \$? = $ac_status" >&5
+   echo "$as_me:12948: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14758,11 +14783,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14761: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14786: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14765: \$? = $ac_status" >&5
+   echo "$as_me:14790: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14970,11 +14995,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14973: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14977: \$? = $ac_status" >&5
+   echo "$as_me:15002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15037,11 +15062,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15040: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15065: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15044: \$? = $ac_status" >&5
+   echo "$as_me:15069: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16979,7 +17004,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16982 "configure"
+#line 17007 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17077,7 +17102,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17080 "configure"
+#line 17105 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19345,6 +19370,7 @@ s,@am__leading_dot@,$am__leading_dot,;t t
 s,@AMTAR@,$AMTAR,;t t
 s,@am__tar@,$am__tar,;t t
 s,@am__untar@,$am__untar,;t t
+s,@JAVA_SOURCE@,$JAVA_SOURCE,;t t
 s,@LN_S@,$LN_S,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
