* configure.in:  Fix typo in help text for --with-gcj. 	Create tab.xml using AC_LINK_FILES rather than AC_OUTPUT.
	* kawa/standard/define.java (scanForDefinitions):  Remove test for
	usingTailCalls.


git-svn-id: svn://sourceware.org/svn/kawa/trunk@2360 5e0a886f-7f45-49c5-bc19-40643649e37f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,7 +17,7 @@ ac_help="$ac_help
 ac_help="$ac_help
   --enable-kawa-frontend   Build "kawa" front-end program using readline"
 ac_help="$ac_help
-  --gjc    Compile Kawa using GCJ (GNU Compiler for Java)"
+  --with-gjc    Compile Kawa using GCJ (GNU Compiler for Java)"
 ac_help="$ac_help
   --disable-xml            Don't build support for XML processing"
 ac_help="$ac_help
@@ -2417,6 +2417,7 @@ JEMACS_VERSION=`echo $VERSION | sed  -e 's/^1/0/'`
 Make_rules="$srcdir/Make-rules"
 
 
+
 trap '' 1 2 15
 cat > confcache <<\EOF
 # This file is a shell script that caches the results of configure
@@ -2542,7 +2543,6 @@ trap 'rm -fr `echo "Makefile gnu/Makefile gnu/bytecode/Makefile gnu/math/Makefil
   kawa/Makefile kawa/lang/Makefile kawa/standard/Makefile kawa/lib/Makefile
   gnu/xquery/Makefile gnu/xquery/lang/Makefile
   gnu/xquery/util/Makefile gnu/xquery/testsuite/Makefile
-  gnu/xquery/testsuite/tab.xml
   doc/Makefile testsuite/Makefile bin/Makefile" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
@@ -2683,7 +2683,6 @@ CONFIG_FILES=\${CONFIG_FILES-"Makefile gnu/Makefile gnu/bytecode/Makefile gnu/ma
   kawa/Makefile kawa/lang/Makefile kawa/standard/Makefile kawa/lib/Makefile
   gnu/xquery/Makefile gnu/xquery/lang/Makefile
   gnu/xquery/util/Makefile gnu/xquery/testsuite/Makefile
-  gnu/xquery/testsuite/tab.xml
   doc/Makefile testsuite/Makefile bin/Makefile"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
@@ -2743,6 +2742,51 @@ s%@INSTALL@%$INSTALL%g
 fi; done
 rm -f conftest.s*
 
+EOF
+
+cat >> $CONFIG_STATUS <<EOF
+ac_sources="gnu/xquery/testsuite/tab.xml.in"
+ac_dests="gnu/xquery/testsuite/tab.xml"
+EOF
+
+cat >> $CONFIG_STATUS <<\EOF
+srcdir=$ac_given_srcdir
+while test -n "$ac_sources"; do
+  set $ac_dests; ac_dest=$1; shift; ac_dests=$*
+  set $ac_sources; ac_source=$1; shift; ac_sources=$*
+
+  echo "linking $srcdir/$ac_source to $ac_dest"
+
+  if test ! -r $srcdir/$ac_source; then
+    { echo "configure: error: $srcdir/$ac_source: File not found" 1>&2; exit 1; }
+  fi
+  rm -f $ac_dest
+
+  # Make relative symlinks.
+  # Remove last slash and all that follows it.  Not all systems have dirname.
+  ac_dest_dir=`echo $ac_dest|sed 's%/[^/][^/]*$%%'`
+  if test "$ac_dest_dir" != "$ac_dest" && test "$ac_dest_dir" != .; then
+    # The dest file is in a subdirectory.
+    test ! -d "$ac_dest_dir" && mkdir "$ac_dest_dir"
+    ac_dest_dir_suffix="/`echo $ac_dest_dir|sed 's%^\./%%'`"
+    # A "../" for each directory in $ac_dest_dir_suffix.
+    ac_dots=`echo $ac_dest_dir_suffix|sed 's%/[^/]*%../%g'`
+  else
+    ac_dest_dir_suffix= ac_dots=
+  fi
+
+  case "$srcdir" in
+  [/$]*) ac_rel_source="$srcdir/$ac_source" ;;
+  *) ac_rel_source="$ac_dots$srcdir/$ac_source" ;;
+  esac
+
+  # Make a symlink if possible; otherwise try a hard link.
+  if ln -s $ac_rel_source $ac_dest 2>/dev/null ||
+    ln $srcdir/$ac_source $ac_dest; then :
+  else
+    { echo "configure: error: can not link $ac_dest to $srcdir/$ac_source" 1>&2; exit 1; }
+  fi
+done
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
